name: "Merge Upstream"
description: "Merge changes from the uppstream repo you had forked from."
author: "eXions"
branding:
  icon: git-merge
  color: black

inputs:
  upstream:
    description: 'Upstream repository owner/name. For example, exions/merge-upstream'
    required: true
  upstream-branch:
    description: 'Upstream branch to merge from. For example, master'
    default: 'master'
  branch:
    description: 'Branch to merge to. For example, master'
    default: 'master'
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}

runs:
  using: "composite"
  steps: 
    - run: | 
        git remote add -f upstream "https://github.com/${{ inputs.upstream }}.git"
        git remote -v
        git branch --all
        git config --list
        git checkout ${{ inputs.branch }}
        git merge --ff-only upstream/${{ inputs.upstream-branch }}
        git push 
      shell: bash
