name: "Merge Upstream"
description: "Merge changes from the uppstream repo you had forked from."
author: "eXions"
branding:
  icon: git-merge
  color: black

inputs:
  upstream:
    description: 'Upstream repository owner/name. For example, exions/merge-upstream'
    required: true
  branch:
    description: 'Branch to merge to. For example, master'
    default: 'master'

runs:
  using: "composite"
  steps: 
    - run: | 
        git remote add -f upstream "https://github.com/${{ inputs.upstream }}.git"
        git merge --ff-only upstream/${{ inputs.branch }}
        git push 
      shell: bash